services:
  postgres:
    image: postgres:12.22
    restart: always
    environment:
      POSTGRES_DB: bdb
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
