apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "simplebank.fullname" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "simplebank.labels" . | nindent 4 }}
data:
  BANK_APP_ENVIRONMENT: {{ .Values.config.app.environment | quote }}
  BANK_APP_HOST: {{ .Values.config.app.host | quote }}
  BANK_APP_PORT: {{ .Values.config.app.port | quote }}
  BANK_POSTGRES_HOST: "{{ include "simplebank.fullname" . }}-postgresql:{{ .Values.postgresql.service.port }}"
  BANK_POSTGRES_SSLMODE: "disable"
  BANK_POSTGRES_AUTOMIGRATE: "true"
