apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "simplebank.fullname" . }}
  labels:
    {{- include "simplebank.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "simplebank.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "simplebank.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "simplebank.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: BANK_POSTGRES_HOST
              value: "{{ include "simplebank.fullname" . }}-postgresql:{{ .Values.postgresql.service.port }}"
            - name: BANK_POSTGRES_DATABASE
              value: {{ .Values.postgresql.auth.database }}
            - name: BANK_POSTGRES_USERNAME
              value: {{ .Values.postgresql.auth.username }}
            - name: BANK_POSTGRES_PASSWORD
              value: {{ .Values.postgresql.auth.password }}
            - name: BANK_POSTGRES_SSLMODE
              value: "disable"
            - name: BANK_POSTGRES_AUTOMIGRATE
              value: "true"
            - name: BANK_APP_ENVIRONMENT
              value: {{ .Values.config.app.environment }}
            - name: BANK_APP_HOST
              value: {{ .Values.config.app.host }}
            - name: BANK_APP_PORT
              value: {{ .Values.config.app.port }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}