apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "simplebank.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.dockerHub.configJson | b64enc | quote }}
