apiVersion: v1
kind: Secret
metadata:
  name: {{ include "simplebank.fullname" . }}-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "simplebank.labels" . | nindent 4 }}
type: Opaque
data:
  BANK_POSTGRES_DATABASE: {{ .Values.postgresql.auth.database | b64enc | quote }}
  BANK_POSTGRES_USERNAME: {{ .Values.postgresql.auth.username | b64enc | quote }}
  BANK_POSTGRES_PASSWORD: {{ .Values.postgresql.auth.password | b64enc | quote }}
