name: Go Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12.22
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: bdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Install dependencies
      run: go mod download

    - name: Run tests
      run: go test -v -cover ./...
      env:
        BANK_POSTGRES_HOST: localhost:5432
        BANK_POSTGRES_DATABASE: bdb
        BANK_POSTGRES_USERNAME: test
        BANK_POSTGRES_PASSWORD: test
        BANK_POSTGRES_SSLMODE: disable
        BANK_POSTGRES_AUTOMIGRATE: true
